version: '3'

services:
  frontend:
    build:
      context: ./app/client/
    container_name: frontend
    ports:
     - "82:80"
    restart: always
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d/:ro

  backend:
    build:
      context: ./app/server/
    container_name: backend
    restart: always
    ports:
      - "3000:3000"

  db:
    image: mongo:5.0.14
    container_name: database
    restart: always
    volumes:
      - ./database/:/data/db/

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
