version: '3'

services:
  frontend:
    image: frontend
    container_name: frontend
    ports:
     - "82:80"
    depends_on:
      - "backend"
      - "db"
    restart: always
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d/:ro

        # certbot:
        #image: certbot/certbot
        # container_name: certbot
        #command: certonly --webroot -w /var/www/certbot --force-renewal --email mohamedalaaelsafy@gmail.com -d sample.modesoventures.com --agree-tos
        # volumes:
        # - ./conf/certbot/conf:/etc/letsencrypt
        #- ./conf/certbot/www:/var/www/certbot

  backend:
    image: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - "db"

  db:
    image: mongo:5.0.14
    container_name: database
    volumes:
      - ./database/:/data/db/
    ports:
      - 8081:8081

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_SITE_BASEURL=/admin
    depends_on:
      - "db"
